server:
  port: 9040
spring:
  application:
    name: mall-product-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3380/mall_product?characterEncoding=utf-8
    username: root
    password: Anbang713
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: false